version: '3.8'

  #Create a docker-compose.override.yml to simplify CLI interactions.
  #This file allows you to run Symfony or Composer commands within the PHP container
  #without needing to prefix each command with docker-compose exec php.

services:
  php:
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["sh", "-c", "exec $0 \"$@\"", "docker-entrypoint.sh"]
