version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: symfony_web
    restart: unless-stopped
    ports:
      - "1998:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokesite
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
